### ISSUE TITLE
COPYING 裡請放 Apache License 全文

### ISSUE THREAD

**Issue by lantw44** [OpenNetworking/gcoin-community#12]
這樣看起來應該比較正常吧，要求使用者要在下載軟體後，自己再另外下載 license 全文來看總是很奇怪的？

**Comment by l1204366** [comment]
![image](https://cloud.githubusercontent.com/assets/8475738/14519675/f159f6d6-0252-11e6-9bd5-012c21ce235b.png)

我看到 他的官網建議這樣子寫，
@lantw44 的意思是說 還是在把他附上比較好嗎

**Comment by lantw44** [comment]
那段短的一般是拿去 source code 檔案開頭放，避免 license 文字佔用太多空間的，應該不是建議大家不附全文。

**Comment by lbyyy** [comment]
solved #115
