### ISSUE TITLE
關於account的定義

### ISSUE THREAD

**Issue by rekiwu** [OpenNetworking/gcoin-community#21]
目前在試用1.1版中，
關於指令中常出現的account，目前有一些疑問。

我先以`getfixedaddress`，查詢結果為`1Cj2ij`  **(address先以前6碼表示)**

接著再`setaccount 1Cj2ij Reki`
但在`getaccountaddress Reki`
卻得到 `176gaG`

花時間找了一下後，發現`listonewalletaddress`的結果是 `176gaG`
而且`getaccount 176gaG`跟`getaccount 1Cj2ij`都是`Reki`
因為我從未用過'176gaG'，所以有些疑問
還請教目前gcoin account的定義為何？

p.s. 其他像`getassetinfo`等新指令，似乎尚無法使用？

**Comment by rekiwu** [comment]
補充
`listaccounts`的結果是
`{
    "" : {
    },
    "Reki" : {
    }
}`

**Comment by lbyyy** [comment]
getassetinfo無法使用是怎樣的情況呢
我這邊看沒啥問題

**Comment by rekiwu** [comment]
我是顯示如下：
`./src/bitcoin-cli -gcoin getassetinfo`
`error: {"code":-1,"message":"getassetinfo\n\n\n\nReturn a JSON object of licenseinfo of color.\n\nArguments:\n1. \"color\"      (numeric, required) The color\n\nResult:\n{\n  \"version\" : n,          (numeric) The version\n  \"name\" : xxx,       (string) The name\n  \"description\" : xxx,       (string) The description\n  \"issuer\" : xxx,       (string) The issuer name\n  \"divisibility\" : true,       (bool) The divisibility\n  \"fee_type\" : n,       (int) The fee type\n  \"fee_rate\" : x.xx,       (double) The fee rate\n  \"fee_collector\" : xxx,       (string) The fee collector address\n  \"upper_limit\" : xxx,       (numeric) The upper limit\n  \"mint_schedule\" : false,       (bool) Have mint schedule or not\n  \"member_control\" : false,       (bool) Have member control or not \n  \"metadata_link\" : xxx,       (string) Hyper link for the metadata \n  \"metadata_hash\" : xxx,       (string) Hash for the metadata \n}\n\nExamples:\n> bitcoin-cli getassetinfo \n> curl --user myusername --data-binary '{\"jsonrpc\": \"1.0\", \"id\":\"curltest\", \"method\": \"getassetinfo\", \"params\": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/\n"}`

**Comment by willliw** [comment]
getassetinfo 後面參數接 color

**Comment by willliw** [comment]
正好在弄先改一下

**Comment by rekiwu** [comment]
謝謝告知
看起來`getassetinfo`內容就是license info ??

**Comment by hihiben** [comment]
是的，`getassetinfo`應該回傳該color所對應到的license info內容

**Comment by hihiben** [comment]
account這邊基本上應該是follow原本bitcoin上面的使用邏輯，gcoin對account這邊沒有太大的更動。
由於在你的流程裡面沒有很詳細的步驟，在keypool裡面沒有key時應該是沒有辦法直接`getaccountaddress`的。
如果你有下`keypoolrefill`的話，`getaccountaddress`會幫你選一個key關聯到這個account並且把它當作這個account的代表key。`setaccount`會把你指定的address關聯到這個account但不會把這個所謂的代表key換掉，只有在你使用了這個address之後才會再另外指定一個address把現在這個替換掉。如果需要看目前所有和這個account有關的address則是用`getaddressesbyaccount`的指令來檢視。

**Comment by rekiwu** [comment]
不好意思，我的流程簡述如下：
重新make一個ver. 1.1的gcoin node
`bitcoind -gcoin -daemon`，`./src/bitcoin-cli -gcoin`來下指令

[1]$`keypoolrefill`
[2]$`getfixedaddress`
回傳`1Cj2ij`
[3]$`setaccount 1Cj2ij Reki`
[4]$`getaccountaddress Reki`
回傳`176gaG`
[5]$`listonewalletaddress`
回傳`176gaG`
[6]$`getaccount 176gaG`
回傳`Reki`
[7]$`getaccount 1Cj2ij`
回傳`Reki`
[8]$`getaddressesbyaccount Reki`
回傳`["176gaG", "1Cj2ij"]`

因為我只有執行過一次`setaccount`，
`Reki`這個account name是在step [3]時才出現，並set給`1Cj2ij`
不太明白為何`176gaG`也被set Reki上去就是了...

因為透過account可能可以用來管理address，所以希望能弄清楚一些。

**Comment by lbyyy** [comment]
簡單來說getaccountaddress就是拿一把沒用過的key把它標成account(Reki)
你先呼叫過getaccountaddress了所以176gaG也因此被標成Reki.

**Comment by rekiwu** [comment]
原來如此
是我會錯意了，以為`getaccountaddress`是查詢用
