### ISSUE TITLE
Dynamic difficulty feature should be opened only when the Alliance member is more than 10. 

### ISSUE THREAD

**Issue by willliw** [OpenNetworking/gcoin-community#24]
As title, 看起來這件事被忽略掉了

**Comment by hihiben** [comment]
原本的機制應該是這樣。
令n為alliance的個數，Dynamic difficulty的運作是藉由往回檢驗前m個block是否有同樣的miner，其中 m = n - 1，若在過去這m個block中有k個同樣的miner，則該次mining的難度為原本的2^k倍。

**Comment by willliw** [comment]
這樣感覺沒有考慮到有些member drop或是沒在挖礦的情況。我認為我們主要要防的應該不是公平性，而是不讓人連贏n個block。我們實驗看看哪個比較適合，之後版本再上。
@l1204366

**Comment by l1204366** [comment]
how about this
threat model example：
20 alliance members
tolerate up to 5 malicious members with 1000x total hashing power
