### ISSUE TITLE
可考慮修改 warning 出現的時機

### ISSUE THREAD

**Issue by l1204366** [OpenNetworking/gcoin-community#31]
連上140.112.29.201:12321之後，
getinfo 會出現以下警告訊息：「check your network connection, 66 blocks received in the last 4 hours (960 expected) at height 759」
但是網路應該其實沒有問題，可能可以修掉一些多餘的warnings

​jerry@jerry-VirtualBox:~/gcoin-community$ ./src/bitcoin-cli -gcoin getinfo 
{ "version" : 1010000, 
"protoc​​olversion" : 70002, 
"walletversion" : 60000, 
"blocks" : 759, 
"timeoffset" : 0, 
"connections" : 1, 
"proxy" : "", 
"difficulty" : 0.00388043, 
"testnet" : false, 
"keypoololdest" : 1461837034, 
"keystoresize" : 1, 
"errors" : "WARNING: check your network connection, 66 blocks received in the last 4 hours (960 expected) at height 759" }

**Comment by hihiben** [comment]
#38
