### ISSUE TITLE
gcoin new release: gcoin1.1.1

### ISSUE THREAD

**Issue by willliw** [OpenNetworking/gcoin-community#48]
- fix cache problem
- fix rpc: sendlicense bug
- update unit test
- remove QT 
- rename:
  - bitcoind -> gcoined
  - bitcoin-cli -> gcoin-cli
  - getasseetinfo -> getlicenseinfo
  - getlicenseinfo -> getlicenselist

**Comment by hanky312** [comment]
筆誤? gocind or gocined
rename:
bitcoind -> gcoined

**Comment by lbyyy** [comment]
solved #77
