### ISSUE TITLE
Build the GCoin 這個步驟做完，在make會出現錯誤

### ISSUE THREAD

**Issue by hanky312** [OpenNetworking/gcoin-community#66]
2個問題
1.
Build the GCoin 這個步驟做完，在make會出現錯誤

cd ~
git clone https://github.com/OpenNetworking/gcoin-community.git
cd ~/gcoin-community 
./autogen.sh --without-gui --without-miniupnpc 
make 

2.
Running 這個步驟bitcoin改gcoin

Place a configure file in ~/.bitcoin/bitcoin.conf with the following contents (you don't need to modify anything)

**Comment by hihiben** [comment]
`make`前需要下`./configure`
這邊再更新一下wiki的部分

**Comment by hanky312** [comment]
謝謝 @hihiben 
目前已完成更新wiki的部分
